% MATLAB Code from Sensor Array Analyzer App
% Generated by MATLAB 9.11 and Phased Array System Toolbox 4.6
% Generated on 11-Dec-2021 22:19:48
% Create a Uniform Linear Array Object
Array = phased.ULA('NumElements',10,...
'ArrayAxis','x');
% The multiplication factor for lambda units to meter conversion
Array.ElementSpacing = 0.5*0.8;
Array.Taper = ones(1,10).';
Elem = phased.CosineAntennaElement;% Create a cosine antenna element
Elem.CosinePower = [1 1];
Elem.FrequencyRange = [0 300000000];
Array.Element = Elem;
Frequency = 300000000;% Assign Frequencies and Propagation Speed
PropagationSpeed = 240000000;
SteeringAngles = [90;0];% Assign Steering Angles
PhaseShiftBits = 0;% Assign Phase shift quantization bits
figure;% Create Figure
viewArray(Array,'ShowNormal',true,...% Plot Array Geometry
 'ShowTaper',false,'ShowIndex','None',...
 'ShowLocalCoordinates',true,'ShowAnnotation',true,...
 'Orientation',[0;0;0]);
Freq3D = 300000000;% Calculate Steering Weights
w = zeros(getNumElements(Array), length(Frequency));% Find the weights
SteerVector = phased.SteeringVector('SensorArray', Array,...
'PropagationSpeed', PropagationSpeed);
for idx = 1:length(Frequency)
   w(:, idx) = step(SteerVector, Frequency(idx), SteeringAngles(:, idx));
end
format = 'polar';% Plot 3d graph
figure;
pattern(Array, Freq3D , 'PropagationSpeed', PropagationSpeed,...
'Type','directivity', 'CoordinateSystem', format,'weights', w(:,1),...
 'ShowArray',false,'ShowLocalCoordinates',true,...
 'ShowColorbar',true,'Orientation',[0;0;0]);
w = zeros(getNumElements(Array), length(Frequency));% Find the weights
for idx = 1:length(Frequency)
   SteerVector = phased.SteeringVector('SensorArray', Array,...
     'PropagationSpeed', PropagationSpeed, ...
     'NumPhaseShifterBits', PhaseShiftBits(idx));
   w(:, idx) = step(SteerVector, Frequency(idx), SteeringAngles(:, idx));
end
format = 'polar';% Plot 2d azimuth graph
cutAngle = 0;
figure;
pattern(Array, Frequency, -180:180, cutAngle, 'PropagationSpeed', PropagationSpeed,...
'Type', 'directivity', 'CoordinateSystem', format ,'weights', w);
w = zeros(getNumElements(Array), length(Frequency));% Find the weights
for idx = 1:length(Frequency)
   SteerVector = phased.SteeringVector('SensorArray', Array,...
      'PropagationSpeed', PropagationSpeed,...
      'NumPhaseShifterBits', PhaseShiftBits(idx));
   w(:, idx) = step(SteerVector, Frequency(idx), SteeringAngles(:, idx));
end
format = 'uv';% Plot U Pattern
figure;
pattern(Array, Frequency, -1:0.01:1, 0, 'PropagationSpeed', PropagationSpeed,...
'Type','directivity','CoordinateSystem', format,'weights', w); % Plot Grating Lobe Diagram
figure;
plotGratingLobeDiagram(Array,Frequency(1),SteeringAngles(:,1),PropagationSpeed);
